"""initial_schema

Revision ID: 296534cd2577
Revises:
Create Date: 2025-11-30 04:28:30.801838

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import String

# revision identifiers, used by Alembic.
revision = "296534cd2577"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("library_id", sa.String(length=32), nullable=False),
        sa.Column("scan_type", sa.String(length=32), nullable=False),
        sa.Column("folder_path", sa.String(length=32), nullable=True),
        sa.Column("link_files", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scanned_files", sa.Integer(), nullable=False),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("processed_files", sa.Integer(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("unmatched_count", sa.Integer(), nullable=False),
        sa.Column("approved_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_import_jobs_scan_type", "import_jobs", ["scan_type"], unique=False)
    op.create_index("idx_import_jobs_status", "import_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_import_jobs_library_id"), "import_jobs", ["library_id"], unique=False)
    op.create_index(op.f("ix_import_jobs_scan_type"), "import_jobs", ["scan_type"], unique=False)
    op.create_index(op.f("ix_import_jobs_status"), "import_jobs", ["status"], unique=False)
    op.create_table(
        "import_pending_files",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("import_job_id", sa.String(length=32), nullable=False),
        sa.Column("file_path", sa.String(length=32), nullable=False),
        sa.Column("file_name", sa.String(length=32), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_extension", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("matched_volume_id", sa.String(length=32), nullable=True),
        sa.Column("matched_issue_id", sa.String(length=32), nullable=True),
        sa.Column("matched_confidence", sa.Float(), nullable=True),
        sa.Column("comicvine_volume_id", sa.Integer(), nullable=True),
        sa.Column("comicvine_issue_id", sa.Integer(), nullable=True),
        sa.Column("comicvine_match_type", sa.String(length=32), nullable=True),
        sa.Column("comicvine_volume_name", sa.String(length=32), nullable=True),
        sa.Column("comicvine_issue_name", sa.String(length=32), nullable=True),
        sa.Column("comicvine_issue_number", sa.String(length=32), nullable=True),
        sa.Column("comicvine_issue_image", sa.String(length=32), nullable=True),
        sa.Column("comicvine_confidence", sa.Float(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=True),
        sa.Column("target_volume_id", sa.String(length=32), nullable=True),
        sa.Column("target_issue_id", sa.String(length=32), nullable=True),
        sa.Column("target_folder_id", sa.String(length=32), nullable=True),
        sa.Column("preview_rename_to", sa.String(length=32), nullable=True),
        sa.Column("preview_convert_to", sa.String(length=32), nullable=True),
        sa.Column("preview_metatag", sa.Boolean(), nullable=False),
        sa.Column("extracted_series", sa.String(length=32), nullable=True),
        sa.Column("extracted_issue_number", sa.String(length=32), nullable=True),
        sa.Column("extracted_year", sa.Integer(), nullable=True),
        sa.Column("extracted_month", sa.String(length=32), nullable=True),
        sa.Column("extracted_volume", sa.String(length=32), nullable=True),
        sa.Column("cv_search_query", sa.String(length=32), nullable=True),
        sa.Column("cv_results_count", sa.Integer(), nullable=True),
        sa.Column("cv_results_sample", sa.String(length=32), nullable=True),
        sa.Column("cv_issue_filter", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_import_pending_files_comicvine_volume",
        "import_pending_files",
        ["comicvine_volume_id"],
        unique=False,
    )
    op.create_index(
        "idx_import_pending_files_job", "import_pending_files", ["import_job_id"], unique=False
    )
    op.create_index(
        "idx_import_pending_files_matched_volume",
        "import_pending_files",
        ["matched_volume_id"],
        unique=False,
    )
    op.create_index(
        "idx_import_pending_files_status", "import_pending_files", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_import_pending_files_action"), "import_pending_files", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_import_pending_files_comicvine_volume_id"),
        "import_pending_files",
        ["comicvine_volume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_pending_files_extracted_series"),
        "import_pending_files",
        ["extracted_series"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_pending_files_import_job_id"),
        "import_pending_files",
        ["import_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_pending_files_matched_issue_id"),
        "import_pending_files",
        ["matched_issue_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_pending_files_matched_volume_id"),
        "import_pending_files",
        ["matched_volume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_pending_files_status"), "import_pending_files", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_import_pending_files_target_issue_id"),
        "import_pending_files",
        ["target_issue_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_pending_files_target_volume_id"),
        "import_pending_files",
        ["target_volume_id"],
        unique=False,
    )
    op.create_table(
        "import_processing_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("import_job_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_import_processing_jobs_import_job",
        "import_processing_jobs",
        ["import_job_id"],
        unique=False,
    )
    op.create_index(
        "idx_import_processing_jobs_status", "import_processing_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_import_processing_jobs_import_job_id"),
        "import_processing_jobs",
        ["import_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_processing_jobs_status"), "import_processing_jobs", ["status"], unique=False
    )
    op.create_table(
        "import_scanning_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("import_job_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_import_scanning_jobs_import_job",
        "import_scanning_jobs",
        ["import_job_id"],
        unique=False,
    )
    op.create_index(
        "idx_import_scanning_jobs_status", "import_scanning_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_import_scanning_jobs_import_job_id"),
        "import_scanning_jobs",
        ["import_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_scanning_jobs_status"), "import_scanning_jobs", ["status"], unique=False
    )
    op.create_table(
        "include_paths",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("library_id", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_include_paths_enabled", "include_paths", ["enabled"], unique=False)
    op.create_index("idx_include_paths_library", "include_paths", ["library_id"], unique=False)
    op.create_index(op.f("ix_include_paths_enabled"), "include_paths", ["enabled"], unique=False)
    op.create_index(
        op.f("ix_include_paths_library_id"), "include_paths", ["library_id"], unique=False
    )
    op.create_table(
        "indexers",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("enable_rss", sa.Boolean(), nullable=False),
        sa.Column("enable_automatic_search", sa.Boolean(), nullable=False),
        sa.Column("enable_interactive_search", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_indexers_builtin", "indexers", ["is_builtin"], unique=False)
    op.create_index("idx_indexers_enabled", "indexers", ["enabled"], unique=False)
    op.create_index("idx_indexers_type", "indexers", ["type"], unique=False)
    op.create_table(
        "libraries",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("library_root", sa.String(length=32), nullable=False),
        sa.Column("default", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_libraries_default", "libraries", ["default"], unique=False)
    op.create_index("idx_libraries_enabled", "libraries", ["enabled"], unique=False)
    op.create_index(op.f("ix_libraries_default"), "libraries", ["default"], unique=False)
    op.create_index(op.f("ix_libraries_enabled"), "libraries", ["enabled"], unique=False)
    op.create_table(
        "library_issues",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("volume_id", sa.String(length=32), nullable=False),
        sa.Column("comicvine_id", sa.Integer(), nullable=True),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=True),
        sa.Column("release_date", sa.String(length=32), nullable=True),
        sa.Column("description", sa.String(length=32), nullable=True),
        sa.Column("site_url", sa.String(length=32), nullable=True),
        sa.Column("image", sa.String(length=32), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("file_path", sa.String(length=32), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_library_issues_comicvine", "library_issues", ["comicvine_id"], unique=False
    )
    op.create_index("idx_library_issues_status", "library_issues", ["status"], unique=False)
    op.create_index("idx_library_issues_volume", "library_issues", ["volume_id"], unique=False)
    op.create_index(
        op.f("ix_library_issues_comicvine_id"), "library_issues", ["comicvine_id"], unique=False
    )
    op.create_index(op.f("ix_library_issues_status"), "library_issues", ["status"], unique=False)
    op.create_index(
        op.f("ix_library_issues_volume_id"), "library_issues", ["volume_id"], unique=False
    )
    op.create_table(
        "library_volumes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("library_id", sa.String(length=32), nullable=False),
        sa.Column("include_path_id", sa.String(length=32), nullable=True),
        sa.Column("comicvine_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("publisher", sa.String(length=32), nullable=True),
        sa.Column("publisher_country", sa.String(length=32), nullable=True),
        sa.Column("description", sa.String(length=32), nullable=True),
        sa.Column("site_url", sa.String(length=32), nullable=True),
        sa.Column("count_of_issues", sa.Integer(), nullable=True),
        sa.Column("image", sa.String(length=32), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("monitor_new_issues", sa.Boolean(), nullable=False),
        sa.Column("folder_name", sa.String(length=32), nullable=True),
        sa.Column("custom_folder", sa.Boolean(), nullable=False),
        sa.Column("date_last_updated", sa.String(length=32), nullable=True),
        sa.Column("is_ended", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_library_volumes_comicvine", "library_volumes", ["comicvine_id"], unique=False
    )
    op.create_index("idx_library_volumes_library", "library_volumes", ["library_id"], unique=False)
    op.create_index("idx_library_volumes_publisher", "library_volumes", ["publisher"], unique=False)
    op.create_index("idx_library_volumes_year", "library_volumes", ["year"], unique=False)
    op.create_index(
        op.f("ix_library_volumes_comicvine_id"), "library_volumes", ["comicvine_id"], unique=False
    )
    op.create_index(
        op.f("ix_library_volumes_include_path_id"),
        "library_volumes",
        ["include_path_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_library_volumes_library_id"), "library_volumes", ["library_id"], unique=False
    )
    op.create_index(
        op.f("ix_library_volumes_publisher"), "library_volumes", ["publisher"], unique=False
    )
    op.create_index(op.f("ix_library_volumes_year"), "library_volumes", ["year"], unique=False)
    op.create_table(
        "weekly_release_items",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("week_id", sa.String(length=32), nullable=False),
        sa.Column("week_start", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("sources", sa.Text(), nullable=True),
        sa.Column("issue_key", sa.String(length=32), nullable=True),
        sa.Column("url", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("publisher", sa.String(length=32), nullable=True),
        sa.Column("release_date", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.String(length=32), nullable=True),
        sa.Column("matched_volume_id", sa.String(length=32), nullable=True),
        sa.Column("matched_issue_id", sa.String(length=32), nullable=True),
        sa.Column("comicvine_volume_id", sa.Integer(), nullable=True),
        sa.Column("comicvine_issue_id", sa.Integer(), nullable=True),
        sa.Column("comicvine_volume_name", sa.String(length=32), nullable=True),
        sa.Column("comicvine_issue_name", sa.String(length=32), nullable=True),
        sa.Column("comicvine_issue_number", sa.String(length=32), nullable=True),
        sa.Column("comicvine_site_url", sa.String(length=32), nullable=True),
        sa.Column("comicvine_cover_date", sa.String(length=32), nullable=True),
        sa.Column("comicvine_confidence", sa.Float(), nullable=True),
        sa.Column("cv_search_query", sa.String(length=32), nullable=True),
        sa.Column("cv_results_count", sa.Integer(), nullable=True),
        sa.Column("cv_results_sample", sa.Text(), nullable=True),
        sa.Column("bundle_id", sa.String(length=32), nullable=True),
        sa.Column("bundle_name", sa.String(length=32), nullable=True),
        sa.Column("download_url", sa.String(length=32), nullable=True),
        sa.Column("pack_file_path", sa.String(length=32), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weekly_release_items_bundle_id"),
        "weekly_release_items",
        ["bundle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_items_comicvine_issue_id"),
        "weekly_release_items",
        ["comicvine_issue_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_items_comicvine_volume_id"),
        "weekly_release_items",
        ["comicvine_volume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_items_issue_key"),
        "weekly_release_items",
        ["issue_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_items_matched_issue_id"),
        "weekly_release_items",
        ["matched_issue_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_items_matched_volume_id"),
        "weekly_release_items",
        ["matched_volume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_items_source"), "weekly_release_items", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_weekly_release_items_status"), "weekly_release_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_weekly_release_items_week_id"), "weekly_release_items", ["week_id"], unique=False
    )
    op.create_index(
        op.f("ix_weekly_release_items_week_start"),
        "weekly_release_items",
        ["week_start"],
        unique=False,
    )
    op.create_table(
        "weekly_release_matching_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("week_id", sa.String(length=32), nullable=False),
        sa.Column("match_type", sa.String(length=32), nullable=False),
        sa.Column("entry_ids", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_weekly_release_matching_jobs_status",
        "weekly_release_matching_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_weekly_release_matching_jobs_type",
        "weekly_release_matching_jobs",
        ["match_type"],
        unique=False,
    )
    op.create_index(
        "idx_weekly_release_matching_jobs_week",
        "weekly_release_matching_jobs",
        ["week_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_matching_jobs_match_type"),
        "weekly_release_matching_jobs",
        ["match_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_matching_jobs_status"),
        "weekly_release_matching_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_matching_jobs_week_id"),
        "weekly_release_matching_jobs",
        ["week_id"],
        unique=False,
    )
    op.create_table(
        "weekly_release_processing_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("week_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_weekly_release_processing_jobs_status",
        "weekly_release_processing_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_weekly_release_processing_jobs_week",
        "weekly_release_processing_jobs",
        ["week_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_processing_jobs_status"),
        "weekly_release_processing_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weekly_release_processing_jobs_week_id"),
        "weekly_release_processing_jobs",
        ["week_id"],
        unique=False,
    )
    op.create_table(
        "weekly_release_weeks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("week_start", sa.String(length=32), nullable=False),
        sa.Column("fetched_at", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("ignored_files", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weekly_release_weeks_week_start"),
        "weekly_release_weeks",
        ["week_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weekly_release_weeks_week_start"), table_name="weekly_release_weeks")
    op.drop_table("weekly_release_weeks")
    op.drop_index(
        op.f("ix_weekly_release_processing_jobs_week_id"),
        table_name="weekly_release_processing_jobs",
    )
    op.drop_index(
        op.f("ix_weekly_release_processing_jobs_status"),
        table_name="weekly_release_processing_jobs",
    )
    op.drop_index(
        "idx_weekly_release_processing_jobs_week", table_name="weekly_release_processing_jobs"
    )
    op.drop_index(
        "idx_weekly_release_processing_jobs_status", table_name="weekly_release_processing_jobs"
    )
    op.drop_table("weekly_release_processing_jobs")
    op.drop_index(
        op.f("ix_weekly_release_matching_jobs_week_id"), table_name="weekly_release_matching_jobs"
    )
    op.drop_index(
        op.f("ix_weekly_release_matching_jobs_status"), table_name="weekly_release_matching_jobs"
    )
    op.drop_index(
        op.f("ix_weekly_release_matching_jobs_match_type"),
        table_name="weekly_release_matching_jobs",
    )
    op.drop_index(
        "idx_weekly_release_matching_jobs_week", table_name="weekly_release_matching_jobs"
    )
    op.drop_index(
        "idx_weekly_release_matching_jobs_type", table_name="weekly_release_matching_jobs"
    )
    op.drop_index(
        "idx_weekly_release_matching_jobs_status", table_name="weekly_release_matching_jobs"
    )
    op.drop_table("weekly_release_matching_jobs")
    op.drop_index(op.f("ix_weekly_release_items_week_start"), table_name="weekly_release_items")
    op.drop_index(op.f("ix_weekly_release_items_week_id"), table_name="weekly_release_items")
    op.drop_index(op.f("ix_weekly_release_items_status"), table_name="weekly_release_items")
    op.drop_index(op.f("ix_weekly_release_items_source"), table_name="weekly_release_items")
    op.drop_index(
        op.f("ix_weekly_release_items_matched_volume_id"), table_name="weekly_release_items"
    )
    op.drop_index(
        op.f("ix_weekly_release_items_matched_issue_id"), table_name="weekly_release_items"
    )
    op.drop_index(op.f("ix_weekly_release_items_issue_key"), table_name="weekly_release_items")
    op.drop_index(
        op.f("ix_weekly_release_items_comicvine_volume_id"), table_name="weekly_release_items"
    )
    op.drop_index(
        op.f("ix_weekly_release_items_comicvine_issue_id"), table_name="weekly_release_items"
    )
    op.drop_index(op.f("ix_weekly_release_items_bundle_id"), table_name="weekly_release_items")
    op.drop_table("weekly_release_items")
    op.drop_index(op.f("ix_library_volumes_year"), table_name="library_volumes")
    op.drop_index(op.f("ix_library_volumes_publisher"), table_name="library_volumes")
    op.drop_index(op.f("ix_library_volumes_library_id"), table_name="library_volumes")
    op.drop_index(op.f("ix_library_volumes_include_path_id"), table_name="library_volumes")
    op.drop_index(op.f("ix_library_volumes_comicvine_id"), table_name="library_volumes")
    op.drop_index("idx_library_volumes_year", table_name="library_volumes")
    op.drop_index("idx_library_volumes_publisher", table_name="library_volumes")
    op.drop_index("idx_library_volumes_library", table_name="library_volumes")
    op.drop_index("idx_library_volumes_comicvine", table_name="library_volumes")
    op.drop_table("library_volumes")
    op.drop_index(op.f("ix_library_issues_volume_id"), table_name="library_issues")
    op.drop_index(op.f("ix_library_issues_status"), table_name="library_issues")
    op.drop_index(op.f("ix_library_issues_comicvine_id"), table_name="library_issues")
    op.drop_index("idx_library_issues_volume", table_name="library_issues")
    op.drop_index("idx_library_issues_status", table_name="library_issues")
    op.drop_index("idx_library_issues_comicvine", table_name="library_issues")
    op.drop_table("library_issues")
    op.drop_index(op.f("ix_libraries_enabled"), table_name="libraries")
    op.drop_index(op.f("ix_libraries_default"), table_name="libraries")
    op.drop_index("idx_libraries_enabled", table_name="libraries")
    op.drop_index("idx_libraries_default", table_name="libraries")
    op.drop_table("libraries")
    op.drop_index("idx_indexers_type", table_name="indexers")
    op.drop_index("idx_indexers_enabled", table_name="indexers")
    op.drop_index("idx_indexers_builtin", table_name="indexers")
    op.drop_table("indexers")
    op.drop_index(op.f("ix_include_paths_library_id"), table_name="include_paths")
    op.drop_index(op.f("ix_include_paths_enabled"), table_name="include_paths")
    op.drop_index("idx_include_paths_library", table_name="include_paths")
    op.drop_index("idx_include_paths_enabled", table_name="include_paths")
    op.drop_table("include_paths")
    op.drop_index(op.f("ix_import_scanning_jobs_status"), table_name="import_scanning_jobs")
    op.drop_index(op.f("ix_import_scanning_jobs_import_job_id"), table_name="import_scanning_jobs")
    op.drop_index("idx_import_scanning_jobs_status", table_name="import_scanning_jobs")
    op.drop_index("idx_import_scanning_jobs_import_job", table_name="import_scanning_jobs")
    op.drop_table("import_scanning_jobs")
    op.drop_index(op.f("ix_import_processing_jobs_status"), table_name="import_processing_jobs")
    op.drop_index(
        op.f("ix_import_processing_jobs_import_job_id"), table_name="import_processing_jobs"
    )
    op.drop_index("idx_import_processing_jobs_status", table_name="import_processing_jobs")
    op.drop_index("idx_import_processing_jobs_import_job", table_name="import_processing_jobs")
    op.drop_table("import_processing_jobs")
    op.drop_index(
        op.f("ix_import_pending_files_target_volume_id"), table_name="import_pending_files"
    )
    op.drop_index(
        op.f("ix_import_pending_files_target_issue_id"), table_name="import_pending_files"
    )
    op.drop_index(op.f("ix_import_pending_files_status"), table_name="import_pending_files")
    op.drop_index(
        op.f("ix_import_pending_files_matched_volume_id"), table_name="import_pending_files"
    )
    op.drop_index(
        op.f("ix_import_pending_files_matched_issue_id"), table_name="import_pending_files"
    )
    op.drop_index(op.f("ix_import_pending_files_import_job_id"), table_name="import_pending_files")
    op.drop_index(
        op.f("ix_import_pending_files_extracted_series"), table_name="import_pending_files"
    )
    op.drop_index(
        op.f("ix_import_pending_files_comicvine_volume_id"), table_name="import_pending_files"
    )
    op.drop_index(op.f("ix_import_pending_files_action"), table_name="import_pending_files")
    op.drop_index("idx_import_pending_files_status", table_name="import_pending_files")
    op.drop_index("idx_import_pending_files_matched_volume", table_name="import_pending_files")
    op.drop_index("idx_import_pending_files_job", table_name="import_pending_files")
    op.drop_index("idx_import_pending_files_comicvine_volume", table_name="import_pending_files")
    op.drop_table("import_pending_files")
    op.drop_index(op.f("ix_import_jobs_status"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_scan_type"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_library_id"), table_name="import_jobs")
    op.drop_index("idx_import_jobs_status", table_name="import_jobs")
    op.drop_index("idx_import_jobs_scan_type", table_name="import_jobs")
    op.drop_table("import_jobs")
    # ### end Alembic commands ###
